### ISSUE TITLE
Thumbnail Generation works in Dolphin but not on Desktop

### ISSUE THREAD

**Issue by newhinton** [unlimitedbacon/stl-thumb-kde#1]
After installing all the deb's, Dolphin creates the thumbnails as expected. However, stl-files on the Desktop are just "empty" and only the text is visible. Is there a setting i need to make to get it working on the Desktop/Workspace?

![grafik](https://user-images.githubusercontent.com/25279821/136714113-480c2233-0894-4900-b2d1-caaa0bd155f1.png)

**Comment by unlimitedbacon** [comment]
I'm not sure why this would be the case. I guess I never noticed because I always have desktop icons disabled.
