### ISSUE TITLE
unable to make on kde neon

### ISSUE THREAD

**Issue by hijak** [unlimitedbacon/stl-thumb-kde#10]
hi im trying to build the package for kde neon but i face this issue

```
✔ ~/Downloads/stl-thumb-kde-0.5.0/build 
08:03 $ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Error at /usr/share/ECM/modules/ECMQueryQt.cmake:84 (message):
  No executable found.  Can't check QT_INSTALL_PREFIX as required
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs6.cmake:199 (ecm_query_qt)
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:15 (include)
  CMakeLists.txt:24 (include)


-- Configuring incomplete, errors occurred!
```

please release the deb package for kde 6

**Comment by unlimitedbacon** [comment]
My guess would be that you're missing a development package or some part of the toolchain. I'll try to spin up Neon in a VM and look into it.

**Comment by hijak** [comment]
any update its a bit of a hindrance

**Comment by unlimitedbacon** [comment]
For some reason Neon keeps freezing when I run it in a VM. Will try a live boot.

**Comment by tozemobile** [comment]
Hi. Any news on how to make the package on kde neon.
Or the deb package for plasma 6.
Thanks

**Comment by Grntrenchman** [comment]
This worked for me after installing the dependencies, they are just named differently:
qt6-base -> qt6-qtbase-devel
kio -> kf6-kio-devel

cmake and extra-modules exist as named otherwise.

**Comment by Grntrenchman** [comment]
unfortunately I can't install:
```
~/Downloads/stl-thumb/stl-thumb-kde/build$ rpm -i ./stl-thumb-kde-0.5.0-Linux.rpm 
error: Failed dependencies:
        libstl_thumb.so()(64bit) is needed by stl-thumb-kde-0.5.0-1.x86_64
~/Downloads/stl-thumb/stl-thumb-kde/build$ ldconfig -p | grep libstl
        libstl_thumb.so (libc6,x86-64) => /lib64/libstl_thumb.so
~/Downloads/stl-thumb/stl-thumb-kde/build$ dnf list stl-thumb
Last metadata expiration check: 0:36:29 ago on Thu 18 Apr 2024 06:55:06 PM PDT.
Installed Packages
stl-thumb.x86_64                                        0.5.0-1                                        @System
```

**Comment by unlimitedbacon** [comment]
I was able to build and uploaded the .deb package
https://github.com/unlimitedbacon/stl-thumb-kde/releases/tag/v0.5.0

These are the build dependencies on Neon:
* build-essential
* qt6base-dev
* kf6-kio-dev

@Grntrenchman I'm not sure why you are trying to use rpm. Neon uses dpkg.

**Comment by Grntrenchman** [comment]
> @Grntrenchman I'm not sure why you are trying to use rpm. Neon is Debian based.

I'm sorry, I confused kde neon with kde plasma.. I'm using noabara (fedora)

**Comment by tozemobile** [comment]
Thanks to all.
And special thanks for unlimitedbacon for the software and the deb file.
I finally got it working with the deb file on KDE Neon 6.0 plasma version 6.0.4 after a few reboots.
Big Thanks.
