### ISSUE TITLE
Refreash for Plasma 6 and Dolphin 24.04.

### ISSUE THREAD

**Issue by TheAdvent78** [unlimitedbacon/stl-thumb-kde#8]
The plugin builds and installs without a problem, just doesn't show up in the file preview settings in dolphin 24.04

**Comment by artkoz** [comment]
I made a fork and it seems to work on Plasma 6.0 (tested on own ArchLinux). Without warranties :)

**Comment by TheAdvent78** [comment]
> I made a fork and it seems to work on Plasma 6.0 (tested on own ArchLinux). Without warranties :)

I can confirm, your fork works with Plasma 6 on Garuda Linux, will close this issue, thanks for your effort.

**Comment by TheAdvent78** [comment]
> I made a fork and it seems to work on Plasma 6.0 (tested on own ArchLinux). Without warranties :)

I can confirm, your fork works with Plasma 6 on Garuda Linux, will close this issue, thanks for your effort.

**Comment by unlimitedbacon** [comment]
Will keep this open until changes are merged into mainline. @artkoz Thank you! Would you mind opening PR for your work?

**Comment by artkoz** [comment]
i made PR, but please check :) only QT6.

**Comment by unlimitedbacon** [comment]
Released v0.5.0. It seems to work fine on Arch, but KDE 6 does not seem to have made it to any other mainstream distros yet, so I have not been able to package or test on them.
